name: Auto Release (standard-version)

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Bump version & tag
    runs-on: ubuntu-latest

    # Avoid infinite loops: skip when the last commit is the release commit made by this workflow
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required so standard-version can see full history

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.7.0

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      # Optional: run tests/lint/build before releasing
      # - name: Lint
      #   run: pnpm lint
      # - name: Build
      #   run: pnpm -w build

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run standard-version
        run: pnpm release

      - name: Push release commit and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags origin main
